# mlflow/Makefile

.PHONY: up down

# Start MLflow service using docker-compose
up:
	docker compose -f docker-compose.yml up -d

# Stop MLflow service using docker-compose
down:
	docker compose -f docker-compose.yml down
