# redis/Makefile

.PHONY: up down

# Start Redis service using docker-compose
up:
	docker compose -f docker-compose.yml up -d

# Stop Redis service using docker-compose
down:
	docker compose -f docker-compose.yml down
