# minio/Makefile

.PHONY: up down

# Start Minio service using docker-compose
up:
	docker compose -f docker-compose.yml up -d

# Stop Minio service using docker-compose
down:
	docker compose -f docker-compose.yml down
