# mysql/Makefile

.PHONY: up down

# Start MySQL service using docker-compose
up:
	docker compose -f docker-compose.yml up -d

# Stop MySQL service using docker-compose
down:
	docker compose -f docker-compose.yml down
