# mongodb/Makefile

.PHONY: up down

# Start MongoDB service using docker-compose
up:
	docker compose -f docker-compose.yml up -d

# Stop MongoDB service using docker-compose
down:
	docker compose -f docker-compose.yml down
